# -*- coding: utf-8 -*-
"""EfficientB3_Test1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NnmaXsXFiigPoOPilee40yDOBjaGlTRq
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
from tensorflow.keras.models import load_model
from tensorflow.keras.applications.efficientnet import preprocess_input

from tensorflow.keras.models import load_model
model = load_model('/content/drive/MyDrive/efficientnetB3_weather.keras')
print("Model loaded successfully")

class_labels = ['cloudy','foggy','rainy','snowy','sunny']

"""# Choose Image (Upload from Computer)"""

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

img = cv2.imread(file_name)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(img)
plt.title("Original Image")
plt.axis("off")

"""# Create Image Variations"""

variations = {}

# RGB (original)
variations["rgb"] = img

# Blur 20%
variations["blur_20"] = cv2.GaussianBlur(img,(9,9),0)

# Blur 40%
variations["blur_40"] = cv2.GaussianBlur(img,(21,21),0)

# Blur 60%
variations["blur_60"] = cv2.GaussianBlur(img,(35,35),0)

# Grayscale
gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
variations["grayscale"] = cv2.cvtColor(gray, cv2.COLOR_GRAY2RGB)

# HSV
hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
variations["hsv"] = cv2.cvtColor(hsv, cv2.COLOR_HSV2RGB)

# LAB
lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
variations["lab"] = cv2.cvtColor(lab, cv2.COLOR_LAB2RGB)

# BGR
variations["bgr"] = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

# RGBA
rgba = cv2.cvtColor(img, cv2.COLOR_RGB2RGBA)
variations["rgba"] = cv2.cvtColor(rgba, cv2.COLOR_RGBA2RGB)

def predict_weather(image):

    image = cv2.resize(image,(300,300))

    img_array = np.expand_dims(image,axis=0)
    img_array = preprocess_input(img_array)

    preds = model.predict(img_array)[0]

    idx = np.argmax(preds)

    return class_labels[idx], preds[idx]

"""# Visualize Image Variations"""

plt.figure(figsize=(14,10))

for i, (name, image) in enumerate(variations.items()):

    # Get prediction
    label, conf = predict_weather(image)

    plt.subplot(3,3,i+1)
    plt.imshow(image)

    plt.title(f"{name}\n{label} ({conf*100:.2f}%)")

    plt.axis("off")

plt.tight_layout()
plt.show()

"""# Run Predictions"""

results = []

for name, image in variations.items():

    label, conf = predict_weather(image)

    results.append({
        "Variation": name,
        "Predicted Class": label,
        "Confidence (%)": round(conf*100,2)
    })

"""# Comparison Table"""

df = pd.DataFrame(results)

df