# -*- coding: utf-8 -*-
"""Finalb3modelreportone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ezu4rKi1JH1HxaMn97XtCjjOeuInoDfs
"""

from google.colab import drive
drive.mount('/content/drive')

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader, random_split
import numpy as np
from tqdm import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

Step 1: Recreate Model Architecture
import torch
import torch.nn as nn
from torchvision import models

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = models.efficientnet_b3(weights=None)

num_features = model.classifier[1].in_features
model.classifier[1] = nn.Linear(num_features, 5)

model = model.to(device)
🔹 Step 2: Load Weights
LOAD_PATH = "/content/drive/MyDrive/final_weather_model_b3.pth"

model.load_state_dict(torch.load(LOAD_PATH, map_location=device))

model.eval()

print("Model loaded successfully!")

LOAD_PATH = "/content/drive/MyDrive/final_weather_model_b3.pth"

checkpoint = torch.load(LOAD_PATH, map_location=device)

model.load_state_dict(checkpoint['model_state_dict'])
class_names = checkpoint['class_names']

model.eval()

print("Model loaded successfully!")

DATASET_PATH = "/content/drive/MyDrive/data"

IMG_SIZE = 300
BATCH_SIZE = 16
VAL_SPLIT = 0.2

from torch.utils.data import Subset

# Load full dataset (no transform yet)
full_dataset = datasets.ImageFolder(DATASET_PATH)

# Split indices
val_size = int(len(full_dataset) * VAL_SPLIT)
train_size = len(full_dataset) - val_size

indices = torch.randperm(len(full_dataset)).tolist()

train_indices = indices[:train_size]
val_indices = indices[train_size:]

# Create separate datasets (🔥 FIX)
train_dataset = Subset(
    datasets.ImageFolder(DATASET_PATH, transform=train_transform),
    train_indices
)

val_dataset = Subset(
    datasets.ImageFolder(DATASET_PATH, transform=val_transform),
    val_indices
)

# DataLoaders (keep optimized)
train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

print("Train size:", len(train_dataset))
print("Val size:", len(val_dataset))

from sklearn.utils.class_weight import compute_class_weight

targets = [label for _, label in dataset.samples]

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(targets),
    y=targets
)

class_weights = torch.tensor(class_weights, dtype=torch.float).to(device)

# soften weights
class_weights = class_weights * 0.7

print("Class Weights:", class_weights)

model = models.efficientnet_b3(weights="IMAGENET1K_V1")

num_features = model.classifier[1].in_features
model.classifier[1] = nn.Linear(num_features, 5)

model = model.to(device)

model.load_state_dict(torch.load(SAVE_PATH, map_location=device))
model.eval()

criterion = nn.CrossEntropyLoss(weight=class_weights)

optimizer = optim.Adam(model.parameters(), lr=1e-4)

scaler = torch.amp.GradScaler("cuda")

print("Optimizer created:", optimizer)

import torch
print("CUDA Available:", torch.cuda.is_available())
print("Device:", torch.device("cuda" if torch.cuda.is_available() else "cpu"))

EPOCHS = 8
best_val_acc = 0

for epoch in range(EPOCHS):

    model.train()
    train_correct = 0
    train_total = 0

    print(f"\nEpoch {epoch+1}/{EPOCHS}")

    for images, labels in tqdm(train_loader):

        images = images.to(device, non_blocking=True)   # 🔥 faster GPU transfer
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad()

        # 🔥 AMP safe usage
        with torch.amp.autocast(device_type="cuda", enabled=(device.type=="cuda")):
            outputs = model(images)
            loss = criterion(outputs, labels)

        # 🔥 scaler safe
        if device.type == "cuda":
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            loss.backward()
            optimizer.step()

        _, predicted = torch.max(outputs, 1)

        train_total += labels.size(0)
        train_correct += (predicted == labels).sum().item()

    train_acc = 100 * train_correct / train_total

    # 🔹 Validation
    model.eval()
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for images, labels in val_loader:

            images = images.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            outputs = model(images)
            _, predicted = torch.max(outputs, 1)

            val_total += labels.size(0)
            val_correct += (predicted == labels).sum().item()

    val_acc = 100 * val_correct / val_total

    print("Train Acc:", train_acc)
    print("Val Acc:", val_acc)

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), "stage1_model.pth")
        print("Best model saved")

for param in model.features[-30:].parameters():
    param.requires_grad = True

optimizer = torch.optim.Adam(model.parameters(), lr=1e-5)

EPOCHS_FINE = 4

for epoch in range(EPOCHS_FINE):

    model.train()
    train_correct = 0
    train_total = 0

    print(f"\nFine Epoch {epoch+1}/{EPOCHS_FINE}")

    for images, labels in tqdm(train_loader):

        images = images.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        optimizer.zero_grad()

        with torch.amp.autocast(device_type="cuda", enabled=(device.type=="cuda")):
            outputs = model(images)
            loss = criterion(outputs, labels)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        _, predicted = torch.max(outputs, 1)

        train_total += labels.size(0)
        train_correct += (predicted == labels).sum().item()

    train_acc = 100 * train_correct / train_total

    # Validation
    model.eval()
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for images, labels in val_loader:

            images = images.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            outputs = model(images)
            _, predicted = torch.max(outputs, 1)

            val_total += labels.size(0)
            val_correct += (predicted == labels).sum().item()

    val_acc = 100 * val_correct / val_total

    print("Train Acc:", train_acc)
    print("Val Acc:", val_acc)

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), "final_model.pth")
        print("Final model saved")

from google.colab import drive
drive.mount('/content/drive')

SAVE_PATH = "/content/drive/MyDrive/final_weather_model_b3.pth"

torch.save({
    'model_state_dict': model.state_dict(),
    'class_names': dataset.classes   # save class labels also
}, SAVE_PATH)

print("Model saved successfully!")

torch.save({
    'model_state_dict': model.state_dict(),
    'val_acc': val_acc
}, "final_model.pth")

"""# CELL A: Track Loss & Accuracy (Modify Training Loop)"""

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

model.eval()

all_preds = []
all_labels = []

with torch.no_grad():
    for images, labels in val_loader:
        images = images.to(device)
        outputs = model(images)
        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.numpy())

# Classification Report
print("\nClassification Report:\n")
print(classification_report(all_labels, all_preds, target_names=dataset.classes))

# Confusion Matrix
cm = confusion_matrix(all_labels, all_preds)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=dataset.classes,
            yticklabels=dataset.classes)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

print("Final Training Accuracy:", train_acc)
print("Best Validation Accuracy:", best_val_acc)
print("Final Validation Accuracy (from predictions):", accuracy_score(all_labels, all_preds))

from google.colab import files
from PIL import Image
import torch.nn.functional as F

uploaded = files.upload()

for img_name in uploaded.keys():
    img = Image.open(img_name).convert('RGB')

    img_tensor = val_transform(img).unsqueeze(0).to(device)

    model.eval()
    with torch.no_grad():
        outputs = model(img_tensor)
        probs = F.softmax(outputs, dim=1)

        top2_prob, top2_idx = torch.topk(probs, 2)

    print("\nTop 2 Predictions:")

    for i in range(2):
        class_name = dataset.classes[top2_idx[0][i]]
        probability = top2_prob[0][i].item() * 100
        print(f"{class_name}: {probability:.2f}%")

from google.colab import files
from PIL import Image
import torch.nn.functional as F
import matplotlib.pyplot as plt

uploaded = files.upload()

for img_name in uploaded.keys():

    # Load image
    img = Image.open(img_name).convert('RGB')

    # Show image
    plt.imshow(img)
    plt.axis('off')
    plt.title("Input Image")
    plt.show()

    # Transform
    img_tensor = val_transform(img).unsqueeze(0).to(device)

    # Prediction
    model.eval()
    with torch.no_grad():
        outputs = model(img_tensor)
        probs = F.softmax(outputs, dim=1)

        top2_prob, top2_idx = torch.topk(probs, 2)

    # Class names
    class_names = dataset.classes   # or define manually if needed

    print("\nTop 2 Predictions:\n")

    for i in range(2):
        class_name = class_names[top2_idx[0][i]]
        probability = top2_prob[0][i].item() * 100
        print(f"{i+1}. {class_name} → {probability:.2f}%")